[package]
name = "nummi"
version = "0.1.0"
authors = ["Bruno Barcarol Guimar√£es <bbgstb@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = {version = "0.10", features = ["blocking", "json"]}
zip = "0.5.5"
csv = "1.1.3"
chrono = "0.4.11"
